In [4]:
import numpy as np

rand_mat = np.random.rand(5)
print(rand_mat * 10)


rand_mat2 = np.random.rand(5, 5)
print(rand_mat2)


[3.45045209 3.9468081  3.16627669 2.56627632 5.75271261]
[[[0.56777598 0.06983229 0.00451937 0.25771623 0.50244994]
  [0.55912526 0.70809321 0.59611504 0.19231702 0.38780594]
  [0.00686733 0.53591249 0.08732538 0.25120882 0.54851392]
  [0.11670389 0.5271179  0.35244878 0.7834458  0.43192141]
  [0.2523245  0.8044261  0.60245067 0.21672582 0.1186636 ]]

 [[0.54376222 0.34419641 0.13851693 0.33038894 0.50526064]
  [0.75073813 0.59410558 0.3412712  0.18344624 0.16979915]
  [0.5799324  0.43697315 0.8144377  0.35348756 0.92242333]
  [0.44394736 0.07323044 0.69306145 0.42744715 0.794756  ]
  [0.16233015 0.6890348  0.60682475 0.49323228 0.65866588]]

 [[0.82152735 0.33794817 0.98966167 0.83314303 0.37794175]
  [0.04586545 0.11751983 0.98126283 0.45344843 0.77105696]
  [0.55307721 0.92093994 0.49151993 0.36535686 0.81834364]
  [0.96803494 0.17421443 0.16016131 0.95354915 0.38045792]
  [0.36048228 0.53983196 0.13415428 0.22785059 0.99144709]]

 [[0.07076165 0.89190453 0.15829746 0.02153036 0.157

In [5]:
print("Mean:", np.mean(rand_mat2))
print("Standar Deviarion:", np.std(rand_mat2))


Mean: 0.46352391627248146
Standar Deviarion: 0.2714266279988567


In [8]:
rand_mat3 = np.random.randint(1, 6, 10)
rand_mat3


array([4, 3, 5, 3, 5, 2, 4, 1, 5, 4])

In [10]:
rand_mat3 = np.random.randint(1, 6, [3, 3])
rand_mat3


array([[3, 4, 2],
       [5, 4, 1],
       [4, 4, 5]])

In [11]:
rand_mat = np.random.rand()
print(rand_mat * 10)


4.691687237376312


In [19]:
nums = np.arange(1, 11)
print(nums)
print("len(nums):", len(nums))
print("nums[:]", nums[:])
print("nums[0:5]", nums[0:5])
print("nums[5:10]", nums[5:10])
print("nums[5:9]", nums[5:9])
print("nums[5:11]", nums[5:11])


[ 1  2  3  4  5  6  7  8  9 10]
len(nums): 10
nums[:] [ 1  2  3  4  5  6  7  8  9 10]
nums[0:5] [1 2 3 4 5]
nums[5:10] [ 6  7  8  9 10]
nums[5:9] [6 7 8 9]
nums[5:11] [ 6  7  8  9 10]


In [60]:
nums = np.arange(1, 11)
print(nums)
print("len(nums):", len(nums))
print("nums[[0,2,4,6,8]] =", nums[[0,2,4,6,8]])
print("nums[[1,3,5,7,9]] =", nums[[1,3,5,7,9]])
print("nums[:] =", nums[:])
print("nums[0:5] =", nums[0:5])
print("nums[5:10] =", nums[5:10])
print("nums[5:9] =", nums[5:9])
print("nums[5:11] =", nums[5:11])

[ 1  2  3  4  5  6  7  8  9 10]
len(nums): 10
nums[[0,2,4,6,8]] = [1 3 5 7 9]
nums[[1,3,5,7,9]] = [ 2  4  6  8 10]
nums[:] = [ 1  2  3  4  5  6  7  8  9 10]
nums[0:5] = [1 2 3 4 5]
nums[5:10] = [ 6  7  8  9 10]
nums[5:9] = [6 7 8 9]
nums[5:11] = [ 6  7  8  9 10]


In [70]:
nums = np.arange(1, 11)
print(nums)
print(nums[nums%2!=0])
print(nums%2!=0)
print(nums[nums%2==0])
print(nums[nums>=5])
print(nums[nums<=5])


[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ True False  True False  True False  True False  True False]
[ 2  4  6  8 10]
[ 5  6  7  8  9 10]
[1 2 3 4 5]


In [71]:
nums = np.arange(1, 31).reshape(3,10)
print(nums)
print(nums[:,0])
print(nums[:][0])
print(nums[1,0])
print(nums[0:2,0])
print(nums[0:3,0])
print()
print(len(nums[0]))
print(int(len(nums[0])/2))
halfArray = int((len(nums[0]))/2)
print(nums[0:halfArray,0:halfArray])
print(nums[0:5,0:5])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[ 1 11 21]
[ 1  2  3  4  5  6  7  8  9 10]
11
[ 1 11]
[ 1 11 21]

10
5
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [72]:
test_array = [10, 11.5, 12, 13.5, 14,15]   
print(test_array[2:3])

[12]
