In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('StockData.csv')

df

stock        date    price
0     AAPL  08-02-2013  67.8542
1     AAPL  11-02-2013  68.5614
2     AAPL  12-02-2013  66.8428
3     AAPL  13-02-2013  66.7156
4     AAPL  14-02-2013  66.6556
...    ...         ...      ...
5031   ZTS  01-02-2018  77.8200
5032   ZTS  02-02-2018  76.7800
5033   ZTS  05-02-2018  73.8300
5034   ZTS  06-02-2018  73.2700
5035   ZTS  07-02-2018  73.8600

[5036 rows x 3 columns]

In [4]:
df.describe()

price
count  5036.000000
mean     73.057030
std      29.011126
min      28.400000
25%      54.067500
50%      69.085000
75%      79.250000
max     179.260000

In [13]:
matrix8 = np.eye(3)
print(matrix8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
lol = df['stock']
lol2 = lol[1:2]
print(len(lol2))
print(lol2)

1
1    AAPL
Name: stock, dtype: object


In [28]:
lol = np.arange(1,101)
print(lol)
print(len(lol))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
100
