In [1]:
import numpy as np

rand_mat = np.random.rand(5)
print(rand_mat * 10)


rand_mat2 = np.random.rand(5, 5)
print(rand_mat2)


[6.80860637 8.66907573 5.51849316 4.99807442 6.82789124]
[[0.24521439 0.5217387  0.76595032 0.722481   0.88014596]
 [0.25659035 0.73172088 0.57727543 0.86545295 0.46024244]
 [0.74741878 0.44638983 0.36570349 0.29050535 0.01127406]
 [0.26363369 0.73610365 0.46953738 0.37137125 0.35645196]
 [0.41462003 0.26597612 0.61486276 0.09802207 0.8392823 ]]


In [2]:
print("Mean:", np.mean(rand_mat2))
print("Standar Deviarion:", np.std(rand_mat2))


Mean: 0.49271860545354756
Standar Deviarion: 0.24077883023828864


In [3]:
rand_mat3 = np.random.randint(1, 6, 10)
rand_mat3


array([4, 5, 4, 4, 4, 2, 3, 1, 5, 3])

In [4]:
rand_mat3 = np.random.randint(1, 6, [3, 3])
rand_mat3


array([[5, 1, 4],
       [1, 4, 1],
       [5, 4, 1]])

In [5]:
rand_mat = np.random.rand()
print(rand_mat * 10)


9.073225357787358


In [6]:
nums = np.arange(1, 11)
print(nums)
print("len(nums):", len(nums))
print("nums[:]", nums[:])
print("nums[0:5]", nums[0:5])
print("nums[5:10]", nums[5:10])
print("nums[5:9]", nums[5:9])
print("nums[5:11]", nums[5:11])


[ 1  2  3  4  5  6  7  8  9 10]
len(nums): 10
nums[:] [ 1  2  3  4  5  6  7  8  9 10]
nums[0:5] [1 2 3 4 5]
nums[5:10] [ 6  7  8  9 10]
nums[5:9] [6 7 8 9]
nums[5:11] [ 6  7  8  9 10]


In [7]:
nums = np.arange(1, 11)
print(nums)
print("len(nums):", len(nums))
print("nums[[0,2,4,6,8]] =", nums[[0, 2, 4, 6, 8]])
print("nums[[1,3,5,7,9]] =", nums[[1, 3, 5, 7, 9]])
print("nums[:] =", nums[:])
print("nums[0:5] =", nums[0:5])
print("nums[5:10] =", nums[5:10])
print("nums[5:9] =", nums[5:9])
print("nums[5:11] =", nums[5:11])


[ 1  2  3  4  5  6  7  8  9 10]
len(nums): 10
nums[[0,2,4,6,8]] = [1 3 5 7 9]
nums[[1,3,5,7,9]] = [ 2  4  6  8 10]
nums[:] = [ 1  2  3  4  5  6  7  8  9 10]
nums[0:5] = [1 2 3 4 5]
nums[5:10] = [ 6  7  8  9 10]
nums[5:9] = [6 7 8 9]
nums[5:11] = [ 6  7  8  9 10]


In [8]:
nums = np.arange(1, 11)
print(nums)
print(nums[nums % 2 != 0])
print(nums % 2 != 0)
print(nums[nums % 2 == 0])
print(nums[nums >= 5])
print(nums[nums <= 5])


[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ True False  True False  True False  True False  True False]
[ 2  4  6  8 10]
[ 5  6  7  8  9 10]
[1 2 3 4 5]


In [9]:
nums = np.arange(1, 31).reshape(3, 10)
print(nums)
print(nums[:, 0])
print(nums[:][0])
print(nums[1, 0])
print(nums[0:2, 0])
print(nums[0:3, 0])
print()
print(len(nums[0]))
print(int(len(nums[0]) / 2))
halfArray = int((len(nums[0])) / 2)
print(nums[0:halfArray, 0:halfArray])
print(nums[0:5, 0:5])


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[ 1 11 21]
[ 1  2  3  4  5  6  7  8  9 10]
11
[ 1 11]
[ 1 11 21]

10
5
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [10]:
test_array = [10, 11.5, 12, 13.5, 14, 15]
print(test_array[2:3])


[12]


In [11]:
test_array = np.array([100, 1105, 172, 135, 147, 153])
test_array[3:] = 500
print(test_array)

np.save("testNumpySave.csv", test_array)
loadedArray = np.load("testNumpySave.csv.npy")
print(loadedArray)


[ 100 1105  172  500  500  500]
[ 100 1105  172  500  500  500]
